services:

  users-service:
    build: ./backend/users-service
    ports:
      - "3001:3001"
    volumes:
      - user-db:/app/database
      - ./nginx/pki/issued/users-service.crt:/run/certs/users-service.crt:ro
      - ./nginx/pki/private/users-service.key:/run/certs/users-service.key:ro
      - ./nginx/pki/ca/ca.crt:/run/certs/ca.crt:ro
    environment:
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}

    networks:
      - transcendence

  auth-service:
    build: ./backend/auth-service
    ports:
    - "3002:3002"
    volumes:
    - auth-db:/app/database
    - ./nginx/pki/issued/auth-service.crt:/run/certs/auth-service.crt:ro
    - ./nginx/pki/private/auth-service.key:/run/certs/auth-service.key:ro
    - ./nginx/pki/ca/ca.crt:/run/certs/ca.crt:ro

    environment:
      - TWO_FA_SECRET=${TWO_FA_SECRET}
      - TRANSCENDENCE_KEY=${TRANSCENDENCE_KEY}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
    networks:
    - transcendence

  blockchain-service:
    build: ./backend/blockchain-service
    ports:
      - "3003:3003"
    volumes:
      - blockchain-db:/app/database  
      - ./nginx/pki/issued/auth-service.crt:/run/certs/blockchain-service.crt:ro
      - ./nginx/pki/private/auth-service.key:/run/certs/blockchain-service.key:ro
      - ./nginx/pki/ca/ca.crt:/run/certs/ca.crt:ro
    environment:
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
    networks:
      - transcendence

  nginx:
    build: .
    depends_on:
      - users-service
      - auth-service
      - blockchain-service
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
    - ./nginx/pki/issued/nginx-4443.crt:/etc/nginx/mtls/server.crt:ro
    - ./nginx/pki/private/nginx-4443.key:/etc/nginx/mtls/server.key:ro
    - ./nginx/pki/ca/ca.crt:/etc/nginx/ca/ca.crt:ro
    - ./nginx/pki/issued/nginx-client.crt:/etc/nginx/mtls/client.crt:ro
    - ./nginx/pki/private/nginx-client.key:/etc/nginx/mtls/client.key:ro
    networks:
      - transcendence

networks:
  transcendence:
    driver: bridge

volumes:
  user-db:
  auth-db:
  blockchain-db:
