services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: npm run start:backend
    ports:
      - "3002:3002"
    networks:
      - appnet

  users:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: npm run start:users
    ports:
      - "3001:3001"
    networks:
      - appnet

  ai:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: npm run start:ai
    ports:
      - "3003:3003"
    networks:
      - appnet

  nginx:
    image: nginx
    ports:
      - "443:443"
    depends_on:
      - backend
      - users
      - ai
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
      - ./frontend:/usr/share/nginx/html
      - ./ssl:/etc/nginx/ssl
    networks:
      - appnet

networks:
  appnet: {}
