FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 5173

ENV NODE_ENV=development

CMD ["pnpm", "dev", "--host", "0.0.0.0", "--port", "5173"]
